// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/v1/analysis/lstm/jobs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/analysis/lstm/jobs.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/analysis/lstm/jobs.post').default>>>>
    }
    '/api/v1/analysis/lstm/jobs/:job_id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/analysis/lstm/jobs/[job_id].get').default>>>>
    }
    '/api/v1/dashboard/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/dashboard/overview.get').default>>>>
    }
    '/api/v1/dashboard/trend': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/dashboard/trend.get').default>>>>
    }
    '/api/v1/geo/reverse': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/geo/reverse.get').default>>>>
    }
    '/api/v1/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/health.get').default>>>>
    }
    '/api/v1/insights/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/insights/generate.post').default>>>>
    }
    '/api/v1/insights/records': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/insights/records.get').default>>>>
    }
    '/api/v1/insights/records/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/insights/records/[id].get').default>>>>
    }
    '/api/v1/map/districts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/map/districts.get').default>>>>
    }
    '/api/v1/map/points': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/map/points.get').default>>>>
    }
    '/api/v1/reports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/reports.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/reports.post').default>>>>
    }
    '/api/v1/reports/:report_id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/reports/[report_id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}